#!/bin/bash
class Faculty
{
float total_sal=0, salary=60000;
}

class HRA extends Faculty
{
float hra=6000;
}

class DA extends HRA
{
float da=4000;
}

class Science extends DA
{
float bonous=4000;
public static void main(String args[])
{
Science obj=new Science();
obj.total_sal=obj.salary+obj.hra+obj.da+obj.bonous;
System.out.println("Total Salary is:"+obj.total_sal);
}
}
